on:
  push:
    tags:
      - '*'


jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steamdeckhomebrew/holo-base:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: "pacman -S --noconfirm --needed jdk11-openjdk python python-setuptools"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: gradle-konan-cache

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          GIT_TAG: ${{ github.ref_name }}

      - uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: build/bundled/*.zip
